version: '3.9'

services:
  bootstrap:
    build:
      context: bootstrap
      dockerfile: build/Dockerfile
    volumes:
      - ./services/.bootstrap.env:/usr/local/bin/app/.env
      - ./bp/data.txt:/usr/local/bin/app/tmp/data.txt # output CIDs will be here (bp/data.txt)
      - ./bp/idp:/usr/local/bin/app/tmp/idp           # input video directories should be here (bp/idp)
    depends_on:
      - ipfs0
      # - ipfs1
      # - ipfs2

  telescope:
    build:
      context: proxy
      dockerfile: build/Dockerfile
    ports:
      - "5050:8080" # HTTP
      - "5051:9090" # metrics
    volumes:
      - proxydata:/usr/local/bin/app/tmp
      - ./services/.proxy.env:/usr/local/bin/app/.env
      - ./public:/usr/local/bin/app/public
    # depends_on:
    #   - bootstrap
    #   - jaeger
    #   - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"    # UI
      - "6831:6831/udp"  # Thrift over UDP
      - "14268:14268"    # HTTP collector
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus
    volumes:
      - ./services/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus UI

  ipfs0:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ipfs0_staging:/export
      - ipfs0_data:/data/ipfs
      - ./services/swarm.key:/data/ipfs/swarm.key
    command: daemon --enable-pubsub-experiment
    environment:
      - IPFS_PROFILE=server

  ipfs1:
    image: ipfs/kubo:latest
    ports:
      - "4002:4001"
      - "4002:4001/udp"
      - "8081:8080"
      - "5002:5001"
    volumes:
      - ipfs1_staging:/export
      - ipfs1_data:/data/ipfs
      - ./services/swarm.key:/data/ipfs/swarm.key
    command: daemon --enable-pubsub-experiment
    environment:
      - IPFS_PROFILE=server

  ipfs2:
    image: ipfs/kubo:latest
    ports:
      - "4003:4001"
      - "4003:4001/udp"
      - "8082:8080"
      - "5003:5001"
    volumes:
      - ipfs2_staging:/export
      - ipfs2_data:/data/ipfs
      - ./services/swarm.key:/data/ipfs/swarm.key
    command: daemon --enable-pubsub-experiment
    environment:
      - IPFS_PROFILE=server

volumes:
  proxydata:
  ipfs0_staging:
  ipfs0_data:
  ipfs1_staging:
  ipfs1_data:
  ipfs2_staging:
  ipfs2_data:
